<?php
return [
    'Reports',
    'Employees',
    'Companies',
    'User List',
    'Roles',
    'Primary company not set',
    'Superuser',
    'Confirmation',
    'Not ok',
    'Not Responded',
    'Confirmed Employee',
    'Tomorrow',
    'Show',
    'Entries',
    'Search:',
    'Previous',
    'Next',
    'Total Necessary',
    'Section',
    'Sub-section',
    'Date',
    'Time',
    'Total',
    'Necessary',
    'Dashboard',
    'Users',
    'Add New User',
    'Name',
    'Email',
    'Date/Time Added',
    'User Roles',
    'Operations',
    'Edit',
    'Edit User',
    'Given Role',
    'Roles',
    'Permissions',
    'Add Permission',
    'Add Role',
    'Add User',
    'Password',
    'Confirm Password',
    'Preferred Language',
    'Add',
    'Update',
    'Update Role',
    'Show',
    'Employees List',
    'Upload',
    'Select Excel File',
    'Upload',
    'Choose File',
    'Customize Your Columns',
    'Close',
    'Save Changes',
    'Master Data',
    'Shift Management',
    'Setting',
    'Skills',
    'Employee Skills',
    'Employee Availability',
    'Skills Master',
    'Enter Skill',
    'Add',
    'All Skills',
    'No. of Employee',
    'Actions',
    'Delete',
    'Rename',
    'Employees List',
    'Upload New',
    'PSI-S Number',
    'Base',
    'For Work',
    'Hire Date',
    'Optional Management',
    'Phoetic Kanji',
    'Name',
    'Cell No',
    'Residence Card Expiry Date',
    'Cancel',
    'PSI-S Number',
    'Save',
    'PSI-S No:',
    'Employee Name',
    'Availability',
    'Weekdays',
    'Sunday',
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday',
    'Available Time',
    'Employee Availability | Add',
    'Companies',
    'Sub-section Shift',
    'Team Leader',
    'Manage Company',
    'Manage',
    'New Company',
    'Existing Company',
    'Company',
    'Company Name',
    'Contact No.',
    'Address',
    'Section',
    'Section Name',
    'Sub-Section',
    'Sub-section Name',
    'Submit',
    'Company Manage',
    'Add More',
    'Update',
    'Shifts',
    'Company Shift Time Table',
    'Add Shifts',
    'Shift Time Table',
    'Start-End Time',
    'Shift | Edit',
    'Start Time',
    'End Time',
    'Leader',
    'Create',
    'Section Manager',
    'Section Shift',
    'Self Sheet',
    'Attendance Management',
    'Company Shift',
    'Pages',
    'Shift',
    'From',
    'To',
    'Created At',
    'View',
    'Action',
    'Generate New',
    'Generator',
    'Start Date',
    'End Date',
    'Generate',
    'Cancel',
    'Time',
    'Type',
    'Date',
    'Number',
    'Staff No.',
    'Country',
    'Telephone No.',
    'Responsible',
    'Confirmation the day before',
    'Confirm 3 hours ago',
    'Ok',
    'Not Ok',
    'No response',
    'Submit',
    'Arrival time in case of late arrival',
    'Reason for late arrival and absence',
    'Call Medium/Through',
    'Comments',
    'Employee Details',
    'Alert Management',
    'Profile',
    'Logout',
];